
services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: opensea_lotto
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d opensea_lotto"]
      interval: 5s
      timeout: 5s
      retries: 12
  app:
    volumes:
      - .:/app
      - /app/node_modules
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      CHOKIDAR_USEPOLLING: "true"
      DATABASE_URL: postgresql://app:app@db:5432/opensea_lotto
      PORT: 8081
    ports:
      - "8081:8081"
      - "5555:5555"
    env_file:
      - .env
    command: sh -c "npm ci && npx prisma db push && npm run dev"
volumes:
  db_data:


